<?php

add_action( 'acf/include_fields', function() {
if ( ! function_exists( 'acf_add_local_field_group' ) ) {
return;
}

acf_add_local_field_group( array(
'key' => 'group_681d466be9063',
'title' => 'CTA',
'fields' => array(
array(
'key' => 'field_681d533ca365c',
'label' => 'CTA',
'name' => 'cta',
'aria-label' => '',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
array(
'key' => 'field_681d534aa365d',
'label' => 'CTA content',
'name' => 'cta_content',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681d5353a365e',
'label' => 'CTA link',
'name' => 'cta_link',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
'allow_in_bindings' => 0,
),
),
),
),
'location' => array(
array(
array(
'param' => 'post_type',
'operator' => '==',
'value' => 'page',
),
),
array(
array(
'param' => 'post_type',
'operator' => '==',
'value' => 'project',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
'key' => 'group_681a2ae29ff74',
'title' => 'Flexible Content',
'fields' => array(
array(
'key' => 'field_681a2ae25fab2',
'label' => 'Flexible content',
'name' => 'flexible_content',
'aria-label' => '',
'type' => 'flexible_content',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layouts' => array(
'layout_681a2efd00df8' => array(
'key' => 'layout_681a2efd00df8',
'name' => 'text_media',
'label' => 'Text-Media',
'display' => 'block',
'sub_fields' => array(
array(
'key' => 'field_681a2efd00df9',
'label' => 'Title',
'name' => 'title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681a2efd00dfa',
'label' => 'First text',
'name' => 'first_text',
'aria-label' => '',
'type' => 'textarea',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'rows' => '',
'placeholder' => '',
'new_lines' => '',
),
array(
'key' => 'field_681a2f2d00dfc',
'label' => 'Second text',
'name' => 'second_text',
'aria-label' => '',
'type' => 'textarea',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'rows' => '',
'placeholder' => '',
'new_lines' => '',
),
array(
'key' => 'field_681a2efd00dfb',
'label' => 'Project image',
'name' => 'project_image',
'aria-label' => '',
'type' => 'image',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
'library' => 'all',
'min_width' => '',
'min_height' => '',
'min_size' => '',
'max_width' => '',
'max_height' => '',
'max_size' => '',
'mime_types' => '',
'allow_in_bindings' => 0,
'preview_size' => 'medium',
),
array(
'key' => 'field_681a3ca3bc49d',
'label' => 'Media position',
'name' => 'media_position',
'aria-label' => '',
'type' => 'select',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'choices' => array(
'left' => 'left',
'right' => 'right',
),
'default_value' => false,
'return_format' => 'value',
'multiple' => 0,
'allow_null' => 0,
'allow_in_bindings' => 0,
'ui' => 0,
'ajax' => 0,
'placeholder' => '',
'create_options' => 0,
'save_options' => 0,
),
),
'min' => '',
'max' => '',
),
'layout_681a2cfd07b45' => array(
'key' => 'layout_681a2cfd07b45',
'name' => 'gallery',
'label' => 'Gallery',
'display' => 'block',
'sub_fields' => array(
array(
'key' => 'field_681a2fe2b94b2',
'label' => 'Gallery title',
'name' => 'gallery_title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681a2d0707b47',
'label' => 'Gallery',
'name' => 'gallery',
'aria-label' => '',
'type' => 'gallery',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
'library' => 'all',
'min' => '',
'max' => '',
'min_width' => '',
'min_height' => '',
'min_size' => '',
'max_width' => '',
'max_height' => '',
'max_size' => '',
'mime_types' => '',
'insert' => 'append',
'preview_size' => 'medium',
),
),
'min' => '',
'max' => '',
),
'layout_681c048d4e55a' => array(
'key' => 'layout_681c048d4e55a',
'name' => 'title-paragraph',
'label' => 'Title-paragraph',
'display' => 'block',
'sub_fields' => array(
array(
'key' => 'field_681cf4df73caf',
'label' => 'Section title',
'name' => 'section_title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681c04b84e55f',
'label' => 'The paragraph',
'name' => 'the_paragraph',
'aria-label' => '',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'table',
'min' => 0,
'max' => 0,
'collapsed' => '',
'button_label' => 'Ajouter un élément',
'rows_per_page' => 20,
'sub_fields' => array(
array(
'key' => 'field_681cf46675efa',
'label' => 'Title',
'name' => 'title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
'parent_repeater' => 'field_681c04b84e55f',
),
array(
'key' => 'field_681cf46b75efb',
'label' => 'Text',
'name' => 'text',
'aria-label' => '',
'type' => 'textarea',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 1,
'rows' => '',
'placeholder' => '',
'new_lines' => '',
'parent_repeater' => 'field_681c04b84e55f',
),
),
),
),
'min' => '',
'max' => '',
),
'layout_681c05e70215f' => array(
'key' => 'layout_681c05e70215f',
'name' => 'paragraphs-list',
'label' => 'Paragraphs-list',
'display' => 'block',
'sub_fields' => array(
array(
'key' => 'field_681cf2eff7c85',
'label' => 'Title',
'name' => 'title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681c05f902161',
'label' => 'The paragraph',
'name' => 'the_paragraph',
'aria-label' => '',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'table',
'min' => 0,
'max' => 0,
'collapsed' => '',
'button_label' => 'Ajouter un élément',
'rows_per_page' => 20,
'sub_fields' => array(
array(
'key' => 'field_681c061502162',
'label' => 'Title',
'name' => 'title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
'parent_repeater' => 'field_681c05f902161',
),
array(
'key' => 'field_681c061c02163',
'label' => 'Text',
'name' => 'text',
'aria-label' => '',
'type' => 'textarea',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 1,
'rows' => '',
'placeholder' => '',
'new_lines' => '',
'parent_repeater' => 'field_681c05f902161',
),
),
),
),
'min' => '',
'max' => '',
),
'layout_681c048f4e55c' => array(
'key' => 'layout_681c048f4e55c',
'name' => 'skills',
'label' => 'Skills',
'display' => 'block',
'sub_fields' => array(
array(
'key' => 'field_681c04ca4e560',
'label' => 'Title',
'name' => 'title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681c04d14e561',
'label' => 'The skill',
'name' => 'the_skill',
'aria-label' => '',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'table',
'min' => 0,
'max' => 0,
'collapsed' => '',
'button_label' => 'Ajouter un élément',
'rows_per_page' => 20,
'sub_fields' => array(
array(
'key' => 'field_681c0525beebe',
'label' => 'Title',
'name' => 'title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
'parent_repeater' => 'field_681c04d14e561',
),
array(
'key' => 'field_681c052bbeebf',
'label' => 'Description',
'name' => 'description',
'aria-label' => '',
'type' => 'textarea',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 1,
'rows' => '',
'placeholder' => '',
'new_lines' => '',
'parent_repeater' => 'field_681c04d14e561',
),
),
),
array(
'key' => 'field_681d41bc1ced4',
'label' => 'CTA',
'name' => 'cta',
'aria-label' => '',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
array(
'key' => 'field_681d41d01ced5',
'label' => 'CTA above',
'name' => 'cta_above',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681d41df1ced6',
'label' => 'CTA content',
'name' => 'cta_content',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681d41e51ced7',
'label' => 'CTA link',
'name' => 'cta_link',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
'allow_in_bindings' => 0,
),
),
),
),
'min' => '',
'max' => '',
),
),
'min' => '',
'max' => '',
'button_label' => 'Ajouter un élément',
),
),
'location' => array(
array(
array(
'param' => 'post_type',
'operator' => '==',
'value' => 'page',
),
),
array(
array(
'param' => 'post_type',
'operator' => '==',
'value' => 'project',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
'key' => 'group_681aac2919804',
'title' => 'Footer EN',
'fields' => array(
array(
'key' => 'field_681aac291ff68',
'label' => 'Navigation',
'name' => 'navigation',
'aria-label' => '',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'table',
'pagination' => 0,
'min' => 0,
'max' => 0,
'collapsed' => '',
'button_label' => 'Ajouter un élément',
'rows_per_page' => 20,
'sub_fields' => array(
array(
'key' => 'field_681aac2920d22',
'label' => 'Link',
'name' => 'link',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => '',
'allow_in_bindings' => 0,
'parent_repeater' => 'field_681aac291ff68',
),
array(
'key' => 'field_681aac2920d2d',
'label' => 'Link title',
'name' => 'link_title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 1,
'placeholder' => '',
'prepend' => '',
'append' => '',
'parent_repeater' => 'field_681aac291ff68',
),
),
),
array(
'key' => 'field_681aac291ff75',
'label' => 'Resources',
'name' => 'resources',
'aria-label' => '',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'table',
'pagination' => 0,
'min' => 0,
'max' => 0,
'collapsed' => '',
'button_label' => 'Ajouter un élément',
'rows_per_page' => 20,
'sub_fields' => array(
array(
'key' => 'field_681aac2924f78',
'label' => 'Link',
'name' => 'link',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => '',
'allow_in_bindings' => 0,
'parent_repeater' => 'field_681aac291ff75',
),
array(
'key' => 'field_681aac2924f83',
'label' => 'Link title',
'name' => 'link_title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 1,
'placeholder' => '',
'prepend' => '',
'append' => '',
'parent_repeater' => 'field_681aac291ff75',
),
),
),
array(
'key' => 'field_681aac291ff7a',
'label' => 'Socials',
'name' => 'socials',
'aria-label' => '',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'table',
'pagination' => 0,
'min' => 0,
'max' => 0,
'collapsed' => '',
'button_label' => 'Ajouter un élément',
'rows_per_page' => 20,
'sub_fields' => array(
array(
'key' => 'field_681aac29288cd',
'label' => 'Link',
'name' => 'link',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
'allow_in_bindings' => 0,
'parent_repeater' => 'field_681aac291ff7a',
),
array(
'key' => 'field_681aac29288d9',
'label' => 'Link title',
'name' => 'link_title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 1,
'placeholder' => '',
'prepend' => '',
'append' => '',
'parent_repeater' => 'field_681aac291ff7a',
),
),
),
array(
'key' => 'field_681aac291ff7f',
'label' => 'Copyrights',
'name' => 'copyrights',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681aafee3a470',
'label' => 'Legal notices',
'name' => 'legal_notices',
'aria-label' => '',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
array(
'key' => 'field_681aafee3a471',
'label' => 'Label',
'name' => 'label',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681aafee3a472',
'label' => 'Link',
'name' => 'link',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
'allow_in_bindings' => 0,
),
),
),
),
'location' => array(
array(
array(
'param' => 'options_page',
'operator' => '==',
'value' => 'site-options-en',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
'key' => 'group_681a4cda6a06a',
'title' => 'Footer FR',
'fields' => array(
array(
'key' => 'field_681a4e8faf16c',
'label' => 'Navigation',
'name' => 'navigation',
'aria-label' => '',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'table',
'pagination' => 0,
'min' => 0,
'max' => 0,
'collapsed' => '',
'button_label' => 'Ajouter un élément',
'rows_per_page' => 20,
'sub_fields' => array(
array(
'key' => 'field_681a4f7faf16d',
'label' => 'Link',
'name' => 'link',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => '',
'allow_in_bindings' => 0,
'parent_repeater' => 'field_681a4e8faf16c',
),
array(
'key' => 'field_681a4fafaf16e',
'label' => 'Link title',
'name' => 'link_title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 1,
'placeholder' => '',
'prepend' => '',
'append' => '',
'parent_repeater' => 'field_681a4e8faf16c',
),
),
),
array(
'key' => 'field_681aa38c5f532',
'label' => 'Resources',
'name' => 'resources',
'aria-label' => '',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'table',
'pagination' => 0,
'min' => 0,
'max' => 0,
'collapsed' => '',
'button_label' => 'Ajouter un élément',
'rows_per_page' => 20,
'sub_fields' => array(
array(
'key' => 'field_681aa38c5f533',
'label' => 'Link',
'name' => 'link',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => '',
'allow_in_bindings' => 0,
'parent_repeater' => 'field_681aa38c5f532',
),
array(
'key' => 'field_681aa38c5f534',
'label' => 'Link title',
'name' => 'link_title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 1,
'placeholder' => '',
'prepend' => '',
'append' => '',
'parent_repeater' => 'field_681aa38c5f532',
),
),
),
array(
'key' => 'field_681aa38e5f535',
'label' => 'Socials',
'name' => 'socials',
'aria-label' => '',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'table',
'pagination' => 0,
'min' => 0,
'max' => 0,
'collapsed' => '',
'button_label' => 'Ajouter un élément',
'rows_per_page' => 20,
'sub_fields' => array(
array(
'key' => 'field_681aa38e5f536',
'label' => 'Link',
'name' => 'link',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
'allow_in_bindings' => 0,
'parent_repeater' => 'field_681aa38e5f535',
),
array(
'key' => 'field_681aa38e5f537',
'label' => 'Link title',
'name' => 'link_title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 1,
'placeholder' => '',
'prepend' => '',
'append' => '',
'parent_repeater' => 'field_681aa38e5f535',
),
),
),
array(
'key' => 'field_681a50bd79636',
'label' => 'Copyrights',
'name' => 'copyrights',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681a50d279637',
'label' => 'Legal notices',
'name' => 'legal_notices',
'aria-label' => '',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
array(
'key' => 'field_681aaf5d646cc',
'label' => 'Label',
'name' => 'label',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681aaf64646cd',
'label' => 'Link',
'name' => 'link',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
'allow_in_bindings' => 0,
),
),
),
),
'location' => array(
array(
array(
'param' => 'options_page',
'operator' => '==',
'value' => 'site-options-fr',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
'key' => 'group_681aac2ac6bb2',
'title' => 'Footer SQ',
'fields' => array(
array(
'key' => 'field_681aac2acd129',
'label' => 'Navigation',
'name' => 'navigation',
'aria-label' => '',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'table',
'pagination' => 0,
'min' => 0,
'max' => 0,
'collapsed' => '',
'button_label' => 'Ajouter un élément',
'rows_per_page' => 20,
'sub_fields' => array(
array(
'key' => 'field_681aac2ace470',
'label' => 'Link',
'name' => 'link',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => '',
'allow_in_bindings' => 0,
'parent_repeater' => 'field_681aac2acd129',
),
array(
'key' => 'field_681aac2ace48f',
'label' => 'Link title',
'name' => 'link_title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 1,
'placeholder' => '',
'prepend' => '',
'append' => '',
'parent_repeater' => 'field_681aac2acd129',
),
),
),
array(
'key' => 'field_681aac2acd13e',
'label' => 'Resources',
'name' => 'resources',
'aria-label' => '',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'table',
'pagination' => 0,
'min' => 0,
'max' => 0,
'collapsed' => '',
'button_label' => 'Ajouter un élément',
'rows_per_page' => 20,
'sub_fields' => array(
array(
'key' => 'field_681aac2ad380a',
'label' => 'Link',
'name' => 'link',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => '',
'allow_in_bindings' => 0,
'parent_repeater' => 'field_681aac2acd13e',
),
array(
'key' => 'field_681aac2ad382c',
'label' => 'Link title',
'name' => 'link_title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 1,
'placeholder' => '',
'prepend' => '',
'append' => '',
'parent_repeater' => 'field_681aac2acd13e',
),
),
),
array(
'key' => 'field_681aac2acd14a',
'label' => 'Socials',
'name' => 'socials',
'aria-label' => '',
'type' => 'repeater',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'table',
'pagination' => 0,
'min' => 0,
'max' => 0,
'collapsed' => '',
'button_label' => 'Ajouter un élément',
'rows_per_page' => 20,
'sub_fields' => array(
array(
'key' => 'field_681aac2ad7be5',
'label' => 'Link',
'name' => 'link',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
'allow_in_bindings' => 0,
'parent_repeater' => 'field_681aac2acd14a',
),
array(
'key' => 'field_681aac2ad7bfc',
'label' => 'Link title',
'name' => 'link_title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 1,
'placeholder' => '',
'prepend' => '',
'append' => '',
'parent_repeater' => 'field_681aac2acd14a',
),
),
),
array(
'key' => 'field_681aac2acd154',
'label' => 'Copyrights',
'name' => 'copyrights',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681aafb5087a3',
'label' => 'Legal notices',
'name' => 'legal_notices',
'aria-label' => '',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
array(
'key' => 'field_681aafb5087a4',
'label' => 'Label',
'name' => 'label',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681aafb5087a5',
'label' => 'Link',
'name' => 'link',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
'allow_in_bindings' => 0,
),
),
),
),
'location' => array(
array(
array(
'param' => 'options_page',
'operator' => '==',
'value' => 'site-options-sq',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
'key' => 'group_6818208dd8866',
'title' => 'Front page',
'fields' => array(
array(
'key' => 'field_6818208ef0466',
'label' => 'First title',
'name' => 'first_title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '50',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 1,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681a1a049ba93',
'label' => 'Second title',
'name' => 'second_title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '50',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681a1a0e9ba94',
'label' => 'Hero quote',
'name' => 'hero_quote',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681a1a199ba95',
'label' => 'My name',
'name' => 'my_name',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681baf9e3381d',
'label' => 'First CTA',
'name' => 'first_cta',
'aria-label' => '',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
array(
'key' => 'field_681bb0a202105',
'label' => 'CTA Text',
'name' => 'cta_text',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681bb0bb02106',
'label' => 'CTA link',
'name' => 'cta_link',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
'allow_in_bindings' => 1,
),
),
),
array(
'key' => 'field_681bb0db02107',
'label' => 'Second CTA',
'name' => 'second_cta',
'aria-label' => '',
'type' => 'group',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'layout' => 'block',
'sub_fields' => array(
array(
'key' => 'field_681bb0db02108',
'label' => 'CTA Text',
'name' => 'cta_text',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681bb0db02109',
'label' => 'CTA link',
'name' => 'cta_link',
'aria-label' => '',
'type' => 'link',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
'allow_in_bindings' => 1,
),
),
),
),
'location' => array(
array(
array(
'param' => 'page_type',
'operator' => '==',
'value' => 'front_page',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
'key' => 'group_681aac5147e85',
'title' => 'General settings EN',
'fields' => array(
array(
'key' => 'field_681aac514fa6a',
'label' => 'Company logo',
'name' => 'company_logo',
'aria-label' => '',
'type' => 'image',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
'library' => 'all',
'min_width' => '',
'min_height' => '',
'min_size' => '',
'max_width' => '',
'max_height' => '',
'max_size' => '',
'mime_types' => '',
'allow_in_bindings' => 0,
'preview_size' => 'medium',
),
array(
'key' => 'field_681aac514fa77',
'label' => 'Company name',
'name' => 'company_name',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681aac514fa7f',
'label' => 'Company phone',
'name' => 'company_phone',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 1,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681aac514fa86',
'label' => 'Company email',
'name' => 'company_email',
'aria-label' => '',
'type' => 'email',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681aac514fa8b',
'label' => 'Company address',
'name' => 'company_address',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681aac514fa96',
'label' => 'Company postal',
'name' => 'company_postal',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681aac514fa9f',
'label' => 'Company country',
'name' => 'company_country',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
),
'location' => array(
array(
array(
'param' => 'options_page',
'operator' => '==',
'value' => 'site-options-en',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
'key' => 'group_681a41ceb9a36',
'title' => 'General settings FR',
'fields' => array(
array(
'key' => 'field_681a41ce6ec1b',
'label' => 'Company logo',
'name' => 'company_logo',
'aria-label' => '',
'type' => 'image',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
'library' => 'all',
'min_width' => '',
'min_height' => '',
'min_size' => '',
'max_width' => '',
'max_height' => '',
'max_size' => '',
'mime_types' => '',
'allow_in_bindings' => 0,
'preview_size' => 'medium',
),
array(
'key' => 'field_681a47b011aa8',
'label' => 'Company name',
'name' => 'company_name',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681a4b0d11aad',
'label' => 'Company phone',
'name' => 'company_phone',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 1,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681a4acc11aac',
'label' => 'Company email',
'name' => 'company_email',
'aria-label' => '',
'type' => 'email',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681aabdce88f0',
'label' => 'Company address',
'name' => 'company_address',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681aabdee88f1',
'label' => 'Company postal',
'name' => 'company_postal',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681a94eb17388',
'label' => 'Company country',
'name' => 'company_country',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
),
'location' => array(
array(
array(
'param' => 'options_page',
'operator' => '==',
'value' => 'site-options-fr',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
'key' => 'group_681aac52e4e43',
'title' => 'General settings SQ',
'fields' => array(
array(
'key' => 'field_681aac52ebf63',
'label' => 'Company logo',
'name' => 'company_logo',
'aria-label' => '',
'type' => 'image',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'return_format' => 'array',
'library' => 'all',
'min_width' => '',
'min_height' => '',
'min_size' => '',
'max_width' => '',
'max_height' => '',
'max_size' => '',
'mime_types' => '',
'allow_in_bindings' => 0,
'preview_size' => 'medium',
),
array(
'key' => 'field_681aac52ebf7b',
'label' => 'Company name',
'name' => 'company_name',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681aac52ebf89',
'label' => 'Company phone',
'name' => 'company_phone',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 1,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681aac52ebf93',
'label' => 'Company email',
'name' => 'company_email',
'aria-label' => '',
'type' => 'email',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681aac52ebf9c',
'label' => 'Company address',
'name' => 'company_address',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681aac52ebfa7',
'label' => 'Company postal',
'name' => 'company_postal',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
array(
'key' => 'field_681aac52ebfb6',
'label' => 'Company country',
'name' => 'company_country',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
),
'location' => array(
array(
array(
'param' => 'options_page',
'operator' => '==',
'value' => 'site-options-sq',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
) );

acf_add_local_field_group( array(
'key' => 'group_681c05716ce15',
'title' => 'Single project',
'fields' => array(
array(
'key' => 'field_681a2fa5d1753',
'label' => 'Project title',
'name' => 'project_title',
'aria-label' => '',
'type' => 'text',
'instructions' => '',
'required' => 0,
'conditional_logic' => 0,
'wrapper' => array(
'width' => '',
'class' => '',
'id' => '',
),
'default_value' => '',
'maxlength' => '',
'allow_in_bindings' => 0,
'placeholder' => '',
'prepend' => '',
'append' => '',
),
),
'location' => array(
array(
array(
'param' => 'post_type',
'operator' => '==',
'value' => 'project',
),
),
),
'menu_order' => 0,
'position' => 'normal',
'style' => 'default',
'label_placement' => 'top',
'instruction_placement' => 'label',
'hide_on_screen' => '',
'active' => true,
'description' => '',
'show_in_rest' => 0,
) );
} );

